# Generated by Django 2.2.4 on 2019-09-22 19:26

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depoimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Nome', max_length=35)),
                ('profissao', models.CharField(default='Profissão', max_length=70)),
                ('profissao_ingles', models.CharField(default='Occupation', max_length=70)),
                ('depoimento', models.TextField(default='Depoimento', max_length=560)),
                ('depoimento_ingles', models.TextField(default='Review', max_length=560)),
                ('alt', models.CharField(default='Descrição para o arquivo da foto', max_length=40)),
                ('imagem', models.ImageField(blank=True, upload_to='_galeria/_depoimentos/')),
                ('cropped', image_cropping.fields.ImageRatioField('imagem', '150x150', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropped')),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(default='Descrição para o arquivo da foto', max_length=40)),
                ('imagem', models.ImageField(blank=True, upload_to='_galeria/_fotos/')),
                ('cropped', image_cropping.fields.ImageRatioField('imagem', '350x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropped')),
            ],
        ),
        migrations.CreateModel(
            name='Seminario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Título do Seminário', max_length=22)),
                ('data', models.DateField()),
                ('local', models.CharField(default='Local do Seminário', max_length=22)),
                ('horario', models.TimeField()),
                ('detalhes', models.TextField(default='Descrição do Seminário', max_length=260)),
            ],
        ),
    ]
