# Generated by Django 2.2.4 on 2019-10-15 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depoimento',
            name='depoimento_ingles',
        ),
        migrations.RemoveField(
            model_name='depoimento',
            name='profissao_ingles',
        ),
    ]
