# Generated by Django 2.2.4 on 2019-10-15 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20191015_1720'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seminario',
        ),
    ]
