# Generated by Django 2.2.4 on 2019-09-22 19:26

from django.db import migrations, models
import embed_video.fields
import image_cropping.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Nome do produto', max_length=16)),
                ('nome_ingles', models.CharField(default='Product name', max_length=16)),
                ('detalhes_da_pagina_inicial', models.CharField(default='Detalhes que serão exibidos na página inicial', max_length=80)),
                ('detalhes_da_pagina_inicial_ingles', models.CharField(default='Details that will be shown in home page', max_length=80)),
                ('imagem_da_pagina_inicial', models.ImageField(blank=True, upload_to='_galeria/_produtos/')),
                ('cropped', image_cropping.fields.ImageRatioField('imagem_da_pagina_inicial', '286x180', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropped')),
                ('mostrar_na_pagina_inicial', models.BooleanField(default=True)),
                ('video_em_gravacao', models.BooleanField(default=False)),
                ('slug', models.SlugField(default=uuid.uuid4, max_length=255, unique=True)),
                ('detalhes', models.TextField(default='Descrição do produto', max_length=2000)),
                ('detalhes_ingles', models.TextField(default='Product description', max_length=2000)),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('link_video_demo', embed_video.fields.EmbedVideoField()),
                ('link_botao_de_compra', models.URLField(default='https://', max_length=300)),
            ],
        ),
    ]
